name: rick_and_morty_flutter_freezed
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0

  http: ^0.13.4

  flutter_bloc: ^8.0.1
  hydrated_bloc: ^8.1.0
  path_provider: ^2.0.9

  cached_network_image: ^3.2.0
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  build_runner: ^2.1.10
  json_serializable: ^6.1.6

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Light.ttf
        - asset: assets/fonts/Raleway-Medium.ttf
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Light.ttf
        - asset: assets/fonts/RobotoMono-Medium.ttf

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
